name: CI

on:
  pull_request:
    branches: ['**']
  push:
    branches: ['main']

permissions:
  contents: read

jobs:
  ci:
    name: Python checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Syntax check (compileall)
        run: python -m compileall -q src
